import type { FlowTree, FlowAiConfig } from "./types";

export const sampleIncidentFlow: FlowTree = {
  flow: {
    id: "flow-incident-1",
    name: "IT-Support ärende",
    description: "Standardflöde för IT-supportärenden",
    category: "IT-Support",
    tags: ["incident", "support"],
    start_step_id: "step-1",
    permissions: { roles: ["user", "editor", "admin"], groups: [] },
    ai_enabled: true,
    ai_mode: "suggestions",
  },
  steps: [
    {
      id: "step-1",
      title: "Beskriv problemet",
      description: "Beskriv vad som hänt och vilken utrustning det gäller",
      type: "questions",
      questions: [
        {
          id: "title",
          label: "Rubrik",
          description: "Kort sammanfattning av problemet",
          required: true,
          input_type: "text",
          validation: { min: 5, max: 200 },
          mapping_key: "title",
        },
        {
          id: "problemDescription",
          label: "Beskrivning",
          description: "Beskriv problemet i detalj",
          required: true,
          input_type: "textarea",
          validation: { min: 10 },
          mapping_key: "description",
        },
        {
          id: "category",
          label: "Kategori",
          required: true,
          input_type: "select",
          options: [
            { value: "IT-Support", label: "IT-Support" },
            { value: "Behörighet", label: "Behörighet" },
            { value: "Beställning", label: "Beställning" },
            { value: "Nätverk", label: "Nätverk" },
          ],
          mapping_key: "category",
        },
      ],
      pre_actions: [],
      post_actions: [],
      transitions: [
        {
          id: "t1-network",
          condition: { type: "equals", field: "answers.category", value: "Nätverk" },
          next_step_id: "step-network",
        },
        {
          id: "t1-default",
          next_step_id: "step-2",
          is_default: true,
        },
      ],
      ui: { columns: 1 },
    },
    {
      id: "step-network",
      title: "Nätverksinformation",
      description: "Specifik information om nätverksproblemet",
      type: "questions",
      questions: [
        {
          id: "networkType",
          label: "Typ av nätverk",
          required: true,
          input_type: "radio",
          options: [
            { value: "vpn", label: "VPN" },
            { value: "wifi", label: "Wi-Fi" },
            { value: "lan", label: "Trådat nätverk" },
          ],
        },
        {
          id: "location",
          label: "Plats",
          required: false,
          input_type: "autocomplete",
          dynamic_options: { action_id: "lookup-locations", label_key: "label", value_key: "id" },
        },
      ],
      pre_actions: [
        {
          id: "lookup-locations",
          name: "Hämta platser",
          type: "lookup",
          trigger: "pre_step",
          input_template: { type: "locations" },
          output_mapping: { "lookups.locations": "result" },
          error_handling: { strategy: "skip", user_message: "Kunde inte hämta platser" },
        },
      ],
      post_actions: [],
      transitions: [{ id: "tn-default", next_step_id: "step-2", is_default: true }],
      ui: { columns: 1 },
    },
    {
      id: "step-2",
      title: "Prioritet och detaljer",
      description: "Ange prioritet och ytterligare information",
      type: "questions",
      questions: [
        {
          id: "priority",
          label: "Prioritet",
          required: true,
          input_type: "select",
          options: [
            { value: "Låg", label: "Låg" },
            { value: "Medium", label: "Medium" },
            { value: "Hög", label: "Hög" },
            { value: "Kritisk", label: "Kritisk" },
          ],
          mapping_key: "priority",
        },
        {
          id: "affectedUsers",
          label: "Antal berörda användare",
          required: false,
          input_type: "number",
          validation: { min: 1, max: 10000 },
        },
        {
          id: "attachment",
          label: "Bifoga fil (valfritt)",
          required: false,
          input_type: "file",
        },
      ],
      pre_actions: [],
      post_actions: [
        {
          id: "enrich-category",
          name: "Föreslå kategori",
          type: "enrichment",
          trigger: "post_step",
          input_template: { text: "{{answers.problemDescription}}" },
          output_mapping: { "derived.suggestedCategory": "result.suggested_category" },
          error_handling: { strategy: "skip" },
        },
      ],
      transitions: [{ id: "t2-default", next_step_id: "step-review", is_default: true }],
      ui: { columns: 2 },
    },
    {
      id: "step-review",
      title: "Granska och skicka",
      description: "Kontrollera att allt stämmer innan du skickar in ärendet",
      type: "review",
      questions: [],
      pre_actions: [],
      post_actions: [],
      transitions: [],
      ui: { columns: 1 },
    },
  ],
};

export const sampleAiConfig: FlowAiConfig = {
  hooks_enabled: {
    on_step_open: true,
    on_answer_change: true,
    on_review: true,
  },
  system_prompt: "Du är en hjälpsam IT-support assistent för kommunens ärendehantering.",
  policies: {
    max_suggestions_per_step: 5,
    require_user_accept: true,
  },
};

// ===== CMDB-GUIDED INCIDENT FLOW =====
export const sampleCmdbGuidedIncidentFlow: FlowTree = {
  flow: {
    id: "flow-cmdb-incident-1",
    name: "CMDB-styrt incidentflöde",
    description: "Incidentflöde som använder CMDB-data för att identifiera berörda CI",
    category: "Incident",
    tags: ["incident", "cmdb", "guided"],
    start_step_id: "cmdb-step-1",
    permissions: { roles: ["user", "editor", "admin"], groups: [] },
    ai_enabled: false,
    ai_mode: "off",
  },
  steps: [
    // Step 1: What type of CI?
    {
      id: "cmdb-step-1",
      title: "Vad gäller problemet?",
      description: "Välj vilken typ av objekt du har problem med",
      type: "questions",
      questions: [
        {
          id: "ciType",
          label: "Typ av objekt",
          description: "Välj den typ av IT-resurs som problemet gäller",
          required: true,
          input_type: "radio",
          options: [
            { value: "device", label: "Dator / Enhet" },
            { value: "application", label: "Applikation" },
            { value: "system", label: "System" },
          ],
        },
      ],
      pre_actions: [],
      post_actions: [],
      transitions: [
        { id: "t-cmdb-1-default", next_step_id: "cmdb-step-2", is_default: true },
      ],
      ui: { columns: 1 },
    },
    // Step 2: Choose the CI (conditional questions)
    {
      id: "cmdb-step-2",
      title: "Välj objekt",
      description: "Välj det specifika objektet som problemet gäller",
      type: "questions",
      questions: [
        {
          id: "deviceId",
          label: "Vilken dator/enhet har du problem med?",
          required: true,
          input_type: "select",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "userDevices",
            labelTemplate: "{{name}} – {{model}} ({{type}})",
            valuePath: "id",
          },
          visibility_conditions: { type: "equals", field: "answers.ciType", value: "device" },
        },
        {
          id: "applicationId",
          label: "Vilken applikation har du problem med?",
          required: true,
          input_type: "select",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "userApplications",
            labelTemplate: "{{name}}",
            valuePath: "id",
          },
          visibility_conditions: { type: "equals", field: "answers.ciType", value: "application" },
        },
        {
          id: "systemId",
          label: "Vilket system har du problem med?",
          required: true,
          input_type: "select",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "userSystems",
            labelTemplate: "{{name}} ({{criticality}})",
            valuePath: "id",
          },
          visibility_conditions: { type: "equals", field: "answers.ciType", value: "system" },
        },
      ],
      pre_actions: [],
      post_actions: [],
      transitions: [
        {
          id: "t-cmdb-2-device",
          condition: { type: "equals", field: "answers.ciType", value: "device" },
          next_step_id: "cmdb-step-3a",
        },
        {
          id: "t-cmdb-2-app",
          condition: { type: "equals", field: "answers.ciType", value: "application" },
          next_step_id: "cmdb-step-3b",
        },
        {
          id: "t-cmdb-2-system",
          condition: { type: "equals", field: "answers.ciType", value: "system" },
          next_step_id: "cmdb-step-3c",
        },
        { id: "t-cmdb-2-default", next_step_id: "cmdb-step-review", is_default: true },
      ],
      ui: { columns: 1 },
    },
    // Step 3A: Device track – installed software + problem description
    {
      id: "cmdb-step-3a",
      title: "Dator: installerade system/appar",
      description: "Välj vilka program som berörs och beskriv problemet",
      type: "questions",
      questions: [
        {
          id: "installedSoftware",
          label: "Vilka program/system berörs?",
          description: "Markera alla program som påverkas av problemet",
          required: false,
          input_type: "multiselect",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "deviceInstalledSoftware",
            params: { deviceId: "{{answers.deviceId}}" },
            labelTemplate: "{{name}} v{{version}} ({{vendor}})",
            valuePath: "id",
            dependsOn: ["deviceId"],
          },
        },
        {
          id: "deviceIssueTitle",
          label: "Kort beskrivning av problemet",
          required: true,
          input_type: "text",
          validation: { min: 5 },
          mapping_key: "title",
        },
        {
          id: "deviceIssueDescription",
          label: "Detaljerad beskrivning",
          required: true,
          input_type: "textarea",
          validation: { min: 10 },
          mapping_key: "description",
        },
      ],
      pre_actions: [],
      post_actions: [],
      transitions: [
        { id: "t-cmdb-3a-default", next_step_id: "cmdb-step-review", is_default: true },
      ],
      ui: { columns: 1 },
    },
    // Step 3B: Application track
    {
      id: "cmdb-step-3b",
      title: "Applikation: beskriv problemet",
      description: "Beskriv problemet med den valda applikationen",
      type: "questions",
      questions: [
        {
          id: "appIssueTitle",
          label: "Kort beskrivning av problemet",
          required: true,
          input_type: "text",
          validation: { min: 5 },
          mapping_key: "title",
        },
        {
          id: "appIssueDescription",
          label: "Detaljerad beskrivning",
          description: "Beskriv felet, eventuell påverkan och hur det uppstod",
          required: true,
          input_type: "textarea",
          validation: { min: 10 },
          mapping_key: "description",
        },
      ],
      pre_actions: [],
      post_actions: [],
      transitions: [
        { id: "t-cmdb-3b-default", next_step_id: "cmdb-step-review", is_default: true },
      ],
      ui: { columns: 1 },
    },
    // Step 3C: System track – servers, APIs, databases + problem
    {
      id: "cmdb-step-3c",
      title: "System: välj berörda CI och beskriv felet",
      description: "Välj vilka servrar, API:er och databaser som berörs",
      type: "questions",
      questions: [
        {
          id: "systemServers",
          label: "Berörda servrar",
          required: false,
          input_type: "multiselect",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "systemServers",
            params: { systemId: "{{answers.systemId}}" },
            labelTemplate: "{{name}} ({{environment}})",
            valuePath: "id",
            dependsOn: ["systemId"],
          },
        },
        {
          id: "systemApis",
          label: "Berörda API:er",
          required: false,
          input_type: "multiselect",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "systemApis",
            params: { systemId: "{{answers.systemId}}" },
            labelTemplate: "{{name}} ({{type}})",
            valuePath: "id",
            dependsOn: ["systemId"],
          },
        },
        {
          id: "systemDatabases",
          label: "Berörda databaser",
          required: false,
          input_type: "multiselect",
          optionsMode: "dynamic",
          dynamicOptions: {
            provider: "cmdb",
            source: "systemDatabases",
            params: { systemId: "{{answers.systemId}}" },
            labelTemplate: "{{name}} ({{type}}, {{environment}})",
            valuePath: "id",
            dependsOn: ["systemId"],
          },
        },
        {
          id: "systemIssueDescription",
          label: "Beskrivning av felet",
          required: true,
          input_type: "textarea",
          validation: { min: 10 },
          mapping_key: "description",
        },
      ],
      pre_actions: [],
      post_actions: [],
      transitions: [
        { id: "t-cmdb-3c-default", next_step_id: "cmdb-step-review", is_default: true },
      ],
      ui: { columns: 1 },
    },
    // Step 4: Review
    {
      id: "cmdb-step-review",
      title: "Granska och skicka",
      description: "Kontrollera att uppgifterna stämmer innan du skickar in ärendet",
      type: "review",
      questions: [],
      pre_actions: [],
      post_actions: [
        {
          id: "create-mock-ticket",
          name: "Skapa mock-ärende",
          type: "automation",
          trigger: "post_step",
          input_template: {
            title: "{{answers.deviceIssueTitle}}{{answers.appIssueTitle}}",
            description: "{{answers.deviceIssueDescription}}{{answers.appIssueDescription}}{{answers.systemIssueDescription}}",
            category: "Incident",
            priority: "Medium",
          },
          output_mapping: { "derived.ticketId": "result.ticketId" },
          error_handling: { strategy: "skip", user_message: "Kunde inte skapa ärende" },
        },
      ],
      transitions: [],
      ui: { columns: 1 },
    },
  ],
};
